"""
Создание всех тестовых таблиц в тестовой схеме для
сохранения данных из СМЭВ по ЕГРЮЛ
Author: Gansior Alexander, gansior@gansior.ru, +79173383804
Starting 2025/08/04
Ending 2025/08/
"""

import sys

# Добавляем путь для подключения modules
new_path = "/opt/airflow2/"
sys.path.append(new_path)
from modules.egrul.com_f import conn_base, get_logger


logger = get_logger()


def all_tables_egrul(var_out, var_schem: str):
    """Создание всех таблиц ЕГРЮЛ
       структура указывается в словаре запросов.
       ключ это название таблицы.

    Args:
        var_out (str): переменная связи с соответсвующей базой
        var_schem (str): название схемы где будут слздаваться 
        таблицы
        
        local_company_pk bpchar(32) первичный ключ это hash от ОГРН организации,
                load_dtm timestamp ДАта загрузки,
                rec_src bpchar(5) Источник данных имеет два значения EGRUL или EGRIP,
                statement_dt date Дата формирования сведений ФНС,
                hash_diff bpchar(32) хэш считается для каждой таблицы свой в зависимости 
                от принятых значимых полей,
    """
    tables = {
        "h_local_company_egrul_main": f"""CREATE TABLE  IF NOT EXISTS {var_schem}.h_local_company_egrul_main (
        ogrn_dt date NULL,
        inn bpchar(10) NULL,
        kpp bpchar(9) NULL,
        opf_code text NULL,
        opf_full_name text NULL,
        opf_catalog text NULL,
        ogrn bpchar(13) NULL,
        local_company_pk bpchar(32) NOT NULL,
        load_dtm timestamp NULL,
        rec_src bpchar(5) NULL,
        statement_dt date NULL,
        CONSTRAINT h_local_company_egrul_main_pkey PRIMARY KEY (local_company_pk)
        );""",
        "s_local_company_actioners_registry_keeper_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_actioners_registry_keeper_info (
                svderjreestrao_derjreestrao_inn bpchar(10) NULL,
                svderjreestrao_derjreestrao_naimulpoln text NULL,
                svderjreestrao_derjreestrao_ogrn text NULL,
                svderjreestrao_derjreestrao_grndata_grn text NULL,
                svderjreestrao_derjreestrao_grndata_valid_from date NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_actioners_registry_keeper_info_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_address_fias_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_address_fias_info (
                svadresul_adresfias_idnom text NULL,
                svadresul_adresfias_indeks bpchar(6) NULL,
                svadresul_adresfias_region bpchar(2) NULL,
                svadresul_adresfias_naimregion text NULL,
                svadresul_adresfias_municipraion_naim text NULL,
                svadresul_adresfias_municipraion_vidkod text NULL,
                svadresul_adresfias_gorodselposelen_naim text NULL,
                svadresul_adresfias_gorodselposelen_vidkod text NULL,
                svadresul_adresfias_naselenpunkt_naim text NULL,
                svadresul_adresfias_naselenpunkt_vid text NULL,
                svadresul_adresfias_elplanstruktur_naim text NULL,
                svadresul_adresfias_elplanstruktur_tip text NULL,
                svadresul_adresfias_eluldorseti_naim text NULL,
                svadresul_adresfias_eluldorseti_tip text NULL,
                svadresul_adresfias_zdanie_nomer text NULL,
                svadresul_adresfias_zdanie_tip text NULL,
                svadresul_adresfias_pomeszdania_nomer text NULL,
                svadresul_adresfias_pomeszdania_tip text NULL,
                svadresul_adresfias_pomeskvart_nomer text NULL,
                svadresul_adresfias_pomeskvart_tip text NULL,
                svadresul_adresfias_grndata_grn text NULL,
                svadresul_adresfias_grndata_valid_from date NULL,
                svadresul_svnedadresul_priznnedadresul int2 NULL,
                svadresul_svnedadresul_tekstnedadresul text NULL,
                svadresul_svnedadresul_grndata_grn text NULL,
                svadresul_svnedadresul_grndata_valid_from date NULL,
                svadresul_svnedadresul_ressudnedadr_data text NULL,
                svadresul_svnedadresul_ressudnedadr_naimsuda text NULL,
                svadresul_svnedadresul_ressudnedadr_nomer text NULL,
                svadresul_svresizmmn_tekstresizmmn text NULL,
                svadresul_svresizmmn_grndata_grn text NULL,
                svadresul_svresizmmn_grndata_valid_from date NULL,
                svadresul_svresizmmn_gorod_naimgorod text NULL,
                svadresul_svresizmmn_gorod_tipgorod text NULL,
                svadresul_svresizmmn_naselpunkt_naimnaselpunkt text NULL,
                svadresul_svresizmmn_naselpunkt_tipnaselpunkt text NULL,
                svadresul_svresizmmn_rajon_naimrajon text NULL,
                svadresul_svresizmmn_rajon_tiprajon text NULL,
                svadresul_svresizmmn_region_naimregion text NULL,
                svadresul_svresizmmn_region_tipregion text NULL,
                fias_guid text NULL,
                hierarchy_fulltext text NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_address_fias_info_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_address_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_address_info (
                svadresul_adresrf_dom text NULL,
                svadresul_adresrf_indeks bpchar(6) NULL,
                svadresul_adresrf_kvart text NULL,
                svadresul_adresrf_kodadrkladr text NULL,
                svadresul_adresrf_kodregion bpchar(2) NULL,
                svadresul_adresrf_korpus text NULL,
                svadresul_adresrf_grndata_grn text NULL,
                svadresul_adresrf_grndata_valid_from date NULL,
                svadresul_adresrf_gorod_naimgorod text NULL,
                svadresul_adresrf_gorod_tipgorod text NULL,
                svadresul_adresrf_naselpunkt_naimnaselpunkt text NULL,
                svadresul_adresrf_naselpunkt_tipnaselpunkt text NULL,
                svadresul_adresrf_rajon_naimrajon text NULL,
                svadresul_adresrf_rajon_tiprajon text NULL,
                svadresul_adresrf_region_naimregion text NULL,
                svadresul_adresrf_region_tipregion text NULL,
                svadresul_adresrf_uliza_naimuliza text NULL,
                svadresul_adresrf_uliza_tipuliza text NULL,
                svadresul_svnedadresul_priznnedadresul int2 NULL,
                svadresul_svnedadresul_tekstnedadresul text NULL,
                svadresul_svnedadresul_grndata_grn text NULL,
                svadresul_svnedadresul_grndata_valid_from date NULL,
                svadresul_svnedadresul_ressudnedadr_data text NULL,
                svadresul_svnedadresul_ressudnedadr_naimsuda text NULL,
                svadresul_svnedadresul_ressudnedadr_nomer text NULL,
                svadresul_svresizmmn_tekstresizmmn text NULL,
                svadresul_svresizmmn_grndata_grn text NULL,
                svadresul_svresizmmn_grndata_valid_from date NULL,
                svadresul_svresizmmn_gorod_naimgorod text NULL,
                svadresul_svresizmmn_gorod_tipgorod text NULL,
                svadresul_svresizmmn_naselpunkt_naimnaselpunkt text NULL,
                svadresul_svresizmmn_naselpunkt_tipnaselpunkt text NULL,
                svadresul_svresizmmn_rajon_naimrajon text NULL,
                svadresul_svresizmmn_rajon_tiprajon text NULL,
                svadresul_svresizmmn_region_naimregion text NULL,
                svadresul_svresizmmn_region_tipregion text NULL,
                hierarchy_fulltext text NULL,
                fias_guid text NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_address_info_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_assignee_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_assignee_info (
                svpreem_inn bpchar(10) NULL,
                svpreem_naimulpoln text NULL,
                svpreem_ogrn bpchar(13) NULL,
                svpreem_grndata_grn text NULL,
                svpreem_grndata_valid_from date NULL,
                svpreem_svulslojnreorg_inn bpchar(10) NULL,
                svpreem_svulslojnreorg_naimulpoln text NULL,
                svpreem_svulslojnreorg_ogrn bpchar(13) NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_assignee_info_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_attorney_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_attorney_info (
                sveddoljnfl_grndataperv_grn text NULL,
                sveddoljnfl_grndataperv_valid_from date NULL,
                sveddoljnfl_svdiskv_datanacdiskv date NULL,
                sveddoljnfl_svdiskv_dataokoncdiskv date NULL,
                sveddoljnfl_svdiskv_datares date NULL,
                sveddoljnfl_svdiskv_grndata_grn text NULL,
                sveddoljnfl_svdiskv_grndata_valid_from date NULL,
                sveddoljnfl_svdoljn_viddoljn text NULL,
                sveddoljnfl_svdoljn_naimviddoljn text NULL,
                sveddoljnfl_svdoljn_naimdoljn text NULL,
                sveddoljnfl_svdoljn_ogrnip text NULL,
                sveddoljnfl_svdoljn_grndata_grn text NULL,
                sveddoljnfl_svdoljn_grndata_valid_from date NULL,
                sveddoljnfl_svneddandoljnfl_priznneddandoljnfl text NULL,
                sveddoljnfl_svneddandoljnfl_tekstneddandoljnfl text NULL,
                sveddoljnfl_svneddandoljnfl_grndata_grn text NULL,
                sveddoljnfl_svneddandoljnfl_grndata_valid_from date NULL,
                sveddoljnfl_svfl_innfl bpchar(12) NULL,
                sveddoljnfl_svfl_ima text NULL,
                sveddoljnfl_svfl_otcestvo text NULL,
                sveddoljnfl_svfl_familia text NULL,
                sveddoljnfl_svfl_grndata_grn text NULL,
                sveddoljnfl_svfl_grndata_valid_from date NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_attorney_info_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_capital_share_company_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_capital_share_company_info (
                svdolaooo_nominstoim text NULL,
                svdolaooo_grndata_grn text NULL,
                svdolaooo_grndata_valid_from date NULL,
                svdolaooo_razmerdoli_drobdesat text NULL,
                svdolaooo_razmerdoli_drobprost_znamenat text NULL,
                svdolaooo_razmerdoli_drobprost_cislit text NULL,
                svdolaooo_razmerdoli_prozent text NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_capital_share_company_info_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_company_authorized_capital_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_company_authorized_capital_info (
                svustkap_naimvidkap text NULL,
                svustkap_sumkap text NULL,
                svustkap_grndata_grn text NULL,
                svustkap_grndata_valid_from date NULL,
                svustkap_dolarubla_znamenat text NULL,
                svustkap_dolarubla_cislit text NULL,
                svustkap_svedumuk_velumuk text NULL,
                svustkap_svedumuk_datares text NULL,
                svustkap_svedumuk_grndata_grn text NULL,
                svustkap_svedumuk_grndata_valid_from date NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_company_authorized_capital_info_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_egrul_history": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_egrul_history (
                svzapegrul_grn text NULL,
                svzapegrul_datazap date NULL,
                svzapegrul_idzap text NULL,
                svzapegrul_vidzap_kodspvz text NULL,
                svzapegrul_vidzap_naimvidzap text NULL,
                svzapegrul_grndatanedpred_grn text NULL,
                svzapegrul_grndatanedpred_datazap text NULL,
                svzapegrul_grndatanedpred_idzap text NULL,
                svzapegrul_svregorg_kodno text NULL,
                svzapegrul_svregorg_naimno text NULL,
                svzapegrul_svsvid_datavydsvid text NULL,
                svzapegrul_svsvid_nomer text NULL,
                svzapegrul_svsvid_seria text NULL,
                svzapegrul_svstatuszap_grndataned_grn text NULL,
                svzapegrul_svstatuszap_grndataned_datazap text NULL,
                svzapegrul_svstatuszap_grndataned_idzap text NULL,
                svzapegrul_svedpreddok_datadok text NULL,
                svzapegrul_svedpreddok_naimdok text NULL,
                svzapegrul_svedpreddok_nomdok text NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_egrul_history_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );
            CREATE INDEX s_local_company_egrul_history_ogrn_idx ON {var_schem}.s_local_company_egrul_history USING btree (ogrn);
            ALTER TABLE {var_schem}.s_local_company_egrul_history ADD CONSTRAINT s_local_company_egrul_history_fkey FOREIGN KEY (local_company_pk) REFERENCES {var_schem}.h_local_company_egrul_main(local_company_pk);""",
        "s_local_company_email_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_email_info (
                svadrelpocty_email text NULL,
                svadrelpocty_grndata_grn text NULL,
                svadrelpocty_grndata_valid_from date NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_email_info_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_founders_info_fl": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_founders_info_fl (
                svucredit_ucrfl_svfl_ima text NULL,
                svucredit_ucrfl_dolaustkap_nominstoim float8 NULL,
                svucredit_ucrfl_svfl_innfl bpchar NULL,
                svucredit_ucrfl_svfl_familia text NULL,
                svucredit_ucrfl_svneddanucr_priznneddanucr int2 NULL,
                svucredit_ucrfl_svfl_otcestvo text NULL,
                load_dtm timestamp NULL,
                ogrn bpchar NULL,
                rec_src bpchar(5) NULL,
                local_company_pk bpchar NOT NULL,
                statement_dt date NULL,
                hash_diff bpchar NOT NULL,
                CONSTRAINT s_local_company_founders_info_fl_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_founders_info_pif": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_founders_info_pif (
                svucredit_ucrpif_dolaustkap_nominstoim float8 NULL,
                svucredit_ucrpif_svneddanucr_priznneddanucr int2 NULL,
                svucredit_ucrpif_svnaimpif_naimpif text NULL,
                load_dtm timestamp NULL,
                ogrn bpchar NULL,
                rec_src bpchar(5) NULL,
                local_company_pk bpchar NOT NULL,
                statement_dt date NULL,
                hash_diff bpchar NOT NULL,
                CONSTRAINT s_local_company_founders_info_pif_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_founders_info_rfsubmo": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_founders_info_rfsubmo (
                svucredit_ucrrfsubmo_dolaustkap_nominstoim float8 NULL,
                svucredit_ucrrfsubmo_vidnaimucr_kodregion text NULL,
                svucredit_ucrrfsubmo_svneddanucr_priznneddanucr int2 NULL,
                svucredit_ucrrfsubmo_vidnaimucr_koducrrfsubmo text NULL,
                svucredit_ucrrfsubmo_vidnaimucr_naimregion text NULL,
                svucredit_ucrrfsubmo_vidnaimucr_naimmo text NULL,
                load_dtm timestamp NULL,
                ogrn bpchar NULL,
                rec_src bpchar(5) NULL,
                local_company_pk bpchar NOT NULL,
                statement_dt date NULL,
                hash_diff bpchar NOT NULL,
                CONSTRAINT s_local_company_founders_info_rfsubmo_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_founders_info_ulin": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_founders_info_ulin (
                svucredit_ucrulin_svneddanucr_priznneddanucr int2 NULL,
                svucredit_ucrulin_svregin_regnomer text NULL,
                svucredit_ucrulin_naiminnul_naimulpoln text NULL,
                svucredit_ucrulin_svregin_adrstr text NULL,
                svucredit_ucrulin_dolaustkap_nominstoim float8 NULL,
                svucredit_ucrulin_svregin_oksm text NULL,
                svucredit_ucrulin_naiminnul_inn bpchar NULL,
                svucredit_ucrulin_naiminnul_ogrn bpchar NULL,
                ogrn bpchar NULL,
                local_company_pk bpchar NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar NOT NULL,
                CONSTRAINT s_local_company_founders_info_ulin_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_founders_info_ulros": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_founders_info_ulros (
                svucredit_ucrulros_naiminnul_inn bpchar NULL,
                svucredit_ucrulros_svneddanucr_priznneddanucr int2 NULL,
                svucredit_ucrulros_dolaustkap_nominstoim float8 NULL,
                svucredit_ucrulros_naiminnul_naimulpoln text NULL,
                svucredit_ucrulros_naiminnul_ogrn bpchar NULL,
                ogrn bpchar NULL,
                local_company_pk bpchar NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar NOT NULL,
                CONSTRAINT s_local_company_founders_info_ulros_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_is_liquidated_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_is_liquidated_info (
                svprekrul_dataprekrul date NULL,
                svprekrul_grndata_grn text NULL,
                svprekrul_grndata_valid_from date NULL,
                svprekrul_svregorg_kodno text NULL,
                svprekrul_svregorg_naimno text NULL,
                svprekrul_spprekrul_kodspprekrul text NULL,
                svprekrul_spprekrul_naimspprekrul text NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_is_liquidated_info_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );
            ALTER TABLE {var_schem}.s_local_company_is_liquidated_info ADD CONSTRAINT s_local_company_is_liquidated_info_fkey FOREIGN KEY (local_company_pk) REFERENCES {var_schem}.h_local_company_egrul_main(local_company_pk);""",
        "s_local_company_legal_name": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_legal_name (
                svnaimul_naimulpoln text NULL,
                svnaimul_naimulsokr text NULL,
                svnaimul_grndata_grn text NULL,
                svnaimul_grndata_valid_from date NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_legal_name_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );
            ALTER TABLE {var_schem}.s_local_company_legal_name ADD CONSTRAINT s_local_company_legal_name_fkey FOREIGN KEY (local_company_pk) REFERENCES {var_schem}.h_local_company_egrul_main(local_company_pk);""",
        "s_local_company_licenses_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_licenses_info (
                svlizenzia_dataliz date NULL,
                svlizenzia_datanacliz date NULL,
                svlizenzia_dataokoncliz date NULL,
                svlizenzia_nomliz text NULL,
                svlizenzia_grndata_grn text NULL,
                svlizenzia_grndata_valid_from date NULL,
                svlizenzia_lizorgvydliz text NULL,
                svlizenzia_mestodejstliz text NULL,
                svlizenzia_naimlizviddeat text NULL,
                svlizenzia_svpriostliz_datapriostliz date NULL,
                svlizenzia_svpriostliz_lizorgpriostliz text NULL,
                svlizenzia_svpriostliz_grndata_grn text NULL,
                svlizenzia_svpriostliz_grndata_valid_from date NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_licenses_info_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );
            ALTER TABLE {var_schem}.s_local_company_licenses_info ADD CONSTRAINT s_local_company_licenses_info_fkey FOREIGN KEY (local_company_pk) REFERENCES {var_schem}.h_local_company_egrul_main(local_company_pk);""",
        "s_local_company_managing_organization_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_managing_organization_info (
                svuprorg_grndataperv_grn text NULL,
                svuprorg_grndataperv_valid_from date NULL,
                svuprorg_naiminnul_inn text NULL,
                svuprorg_naiminnul_naimulpoln text NULL,
                svuprorg_naiminnul_ogrn text NULL,
                svuprorg_naiminnul_grndata_grn text NULL,
                svuprorg_naiminnul_grndata_valid_from date NULL,
                svuprorg_predinul_grndataperv_grn text NULL,
                svuprorg_predinul_grndataperv_valid_from date NULL,
                svuprorg_predinul_svfl_innfl text NULL,
                svuprorg_predinul_svfl_ima text NULL,
                svuprorg_predinul_svfl_otcestvo text NULL,
                svuprorg_predinul_svfl_familia text NULL,
                svuprorg_predinul_svfl_grndata_grn text NULL,
                svuprorg_predinul_svfl_grndata_valid_from date NULL,
                svuprorg_svneddanuprorg_priznneddanuprorg text NULL,
                svuprorg_svneddanuprorg_tekstneddanuprorg text NULL,
                svuprorg_svneddanuprorg_grndata_grn text NULL,
                svuprorg_svneddanuprorg_grndata_valid_from date NULL,
                svuprorg_svregin_adrstr text NULL,
                svuprorg_svregin_datareg text NULL,
                svuprorg_svregin_naimregorg text NULL,
                svuprorg_svregin_naimstran text NULL,
                svuprorg_svregin_oksm text NULL,
                svuprorg_svregin_regnomer text NULL,
                svuprorg_svregin_grndata_grn text NULL,
                svuprorg_svregin_grndata_valid_from date NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_managing_organization_info_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_okveds_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_okveds_info (
                svokved_svokveddop_kodokved text NULL,
                svokved_svokveddop_naimokved text NULL,
                svokved_svokveddop_prversokved int4 NULL,
                svokved_svokveddop_grndata_grn text NULL,
                svokved_svokveddop_grndata_valid_from date NULL,
                svokved_svokvedosn_kodokved text NULL,
                svokved_svokvedosn_naimokved text NULL,
                svokved_svokvedosn_prversokved int4 NULL,
                svokved_svokvedosn_grndata_grn text NULL,
                svokved_svokvedosn_grndata_valid_from date NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_okveds_info_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );
            CREATE INDEX s_local_company_okveds_info_ogrn_idx ON {var_schem}.s_local_company_okveds_info USING btree (ogrn);
            ALTER TABLE {var_schem}.s_local_company_okveds_info ADD CONSTRAINT s_local_company_okveds_info_fkey FOREIGN KEY (local_company_pk) REFERENCES {var_schem}.h_local_company_egrul_main(local_company_pk);""",
        "s_local_company_pension_fund_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_pension_fund_info (
                svregpf_datareg date NULL,
                svregpf_regnompf text NULL,
                svregpf_grndata_grn text NULL,
                svregpf_grndata_valid_from date NULL,
                svregpf_svorgpf_kodpf bpchar(6) NULL,
                svregpf_svorgpf_naimpf text NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_pension_fund_info_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_predecessor_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_predecessor_info (
                svpreds_inn bpchar(10) NULL,
                svpreds_naimulpoln text NULL,
                svpreds_ogrn text NULL,
                svpreds_grndata_grn text NULL,
                svpreds_grndata_valid_from date NULL,
                svpreds_svulslojnreorg_inn bpchar(10) NULL,
                svpreds_svulslojnreorg_naimulpoln text NULL,
                svpreds_svulslojnreorg_ogrn bpchar(13) NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_predecessor_info_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_registration_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_registration_info (
                svobrul_dataogrn date NULL,
                svobrul_datareg date NULL,
                svobrul_naimro text NULL,
                svobrul_ogrn bpchar(13) NULL,
                svobrul_regnom text NULL,
                svobrul_grndata_grn text NULL,
                svobrul_grndata_valid_from date NULL,
                svobrul_spobrul_kodspobrul text NULL,
                svobrul_spobrul_naimspobrul text NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_registration_info_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_registrator_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_registrator_info (
                svregorg_adrro text NULL,
                svregorg_kodno text NULL,
                svregorg_naimno text NULL,
                svregorg_grndata_grn text NULL,
                svregorg_grndata_valid_from date NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_registrator_info_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_reorganisation_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_reorganisation_info (
                svreorg_grndata_grn text NULL,
                svreorg_grndata_valid_from date NULL,
                svreorg_svreorgul_inn bpchar(10) NULL,
                svreorg_svreorgul_naimulpoln text NULL,
                svreorg_svreorgul_ogrn bpchar(13) NULL,
                svreorg_svreorgul_sostulposle text NULL,
                svreorg_svstatus_kodstatusul text NULL,
                svreorg_svstatus_naimstatusul text NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_reorganisation_info_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_social_insurance_fund_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_social_insurance_fund_info (
                svregfss_datareg date NULL,
                svregfss_regnomfss bpchar(15) NULL,
                svregfss_grndata_grn text NULL,
                svregfss_grndata_valid_from date NULL,
                svregfss_svorgfss_kodfss bpchar(4) NULL,
                svregfss_svorgfss_naimfss text NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_social_insurance_fund_info_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_state_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_state_info (
                svstatus_grndata_grn text NULL,
                svstatus_grndata_valid_from date NULL,
                svstatus_svresisklul_datapublikazii date NULL,
                svstatus_svresisklul_datares date NULL,
                svstatus_svresisklul_nomerjurnala text NULL,
                svstatus_svresisklul_nomerres text NULL,
                svstatus_svstatus_kodstatusul int4 NULL,
                svstatus_svstatus_naimstatusul text NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_state_info_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "s_local_company_subdivisions_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_subdivisions_info (
                svpodrazd_svpredstav_adrmnin_adrin text NULL,
                svpodrazd_svpredstav_adrmnin_naimstran text NULL,
                svpodrazd_svpredstav_adrmnin_oksm text NULL,
                svpodrazd_svpredstav_adrmnin_grndata_grn text NULL,
                svpodrazd_svpredstav_adrmnin_grndata_valid_from date NULL,
                svpodrazd_svpredstav_adrmnrf_dom text NULL,
                svpodrazd_svpredstav_adrmnrf_indeks text NULL,
                svpodrazd_svpredstav_adrmnrf_kvart text NULL,
                svpodrazd_svpredstav_adrmnrf_kodadrkladr text NULL,
                svpodrazd_svpredstav_adrmnrf_kodregion text NULL,
                svpodrazd_svpredstav_adrmnrf_korpus text NULL,
                svpodrazd_svpredstav_adrmnrf_grndata_grn text NULL,
                svpodrazd_svpredstav_adrmnrf_grndata_valid_from date NULL,
                svpodrazd_svpredstav_adrmnrf_gorod_naimgorod text NULL,
                svpodrazd_svpredstav_adrmnrf_gorod_tipgorod text NULL,
                svpodrazd_svpredstav_adrmnrf_naselpunkt_naimnaselpunkt text NULL,
                svpodrazd_svpredstav_adrmnrf_naselpunkt_tipnaselpunkt text NULL,
                svpodrazd_svpredstav_adrmnrf_rajon_naimrajon text NULL,
                svpodrazd_svpredstav_adrmnrf_rajon_tiprajon text NULL,
                svpodrazd_svpredstav_adrmnrf_region_naimregion text NULL,
                svpodrazd_svpredstav_adrmnrf_region_tipregion text NULL,
                svpodrazd_svpredstav_adrmnrf_uliza_naimuliza text NULL,
                svpodrazd_svpredstav_adrmnrf_uliza_tipuliza text NULL,
                svpodrazd_svpredstav_grndataperv_grn text NULL,
                svpodrazd_svpredstav_grndataperv_valid_from date NULL,
                svpodrazd_svpredstav_svnaim_naimpoln text NULL,
                svpodrazd_svpredstav_svnaim_grndata_grn text NULL,
                svpodrazd_svpredstav_svnaim_grndata_valid_from date NULL,
                svpodrazd_svfilial_adrmnin_adrin text NULL,
                svpodrazd_svfilial_adrmnin_naimstran text NULL,
                svpodrazd_svfilial_adrmnin_oksm text NULL,
                svpodrazd_svfilial_adrmnin_grndata_grn text NULL,
                svpodrazd_svfilial_adrmnin_grndata_valid_from date NULL,
                svpodrazd_svfilial_adrmnrf_dom text NULL,
                svpodrazd_svfilial_adrmnrf_indeks text NULL,
                svpodrazd_svfilial_adrmnrf_kvart text NULL,
                svpodrazd_svfilial_adrmnrf_kodadrkladr text NULL,
                svpodrazd_svfilial_adrmnrf_kodregion text NULL,
                svpodrazd_svfilial_adrmnrf_korpus text NULL,
                svpodrazd_svfilial_adrmnrf_grndata_grn text NULL,
                svpodrazd_svfilial_adrmnrf_grndata_valid_from text NULL,
                svpodrazd_svfilial_adrmnrf_gorod_naimgorod text NULL,
                svpodrazd_svfilial_adrmnrf_gorod_tipgorod text NULL,
                svpodrazd_svfilial_adrmnrf_naselpunkt_naimnaselpunkt text NULL,
                svpodrazd_svfilial_adrmnrf_naselpunkt_tipnaselpunkt text NULL,
                svpodrazd_svfilial_adrmnrf_rajon_naimrajon text NULL,
                svpodrazd_svfilial_adrmnrf_rajon_tiprajon text NULL,
                svpodrazd_svfilial_adrmnrf_region_naimregion text NULL,
                svpodrazd_svfilial_adrmnrf_region_tipregion text NULL,
                svpodrazd_svfilial_adrmnrf_uliza_naimuliza text NULL,
                svpodrazd_svfilial_adrmnrf_uliza_tipuliza text NULL,
                svpodrazd_svfilial_grndataperv_grn text NULL,
                svpodrazd_svfilial_grndataperv_valid_from date NULL,
                svpodrazd_svfilial_svnaim_naimpoln text NULL,
                svpodrazd_svfilial_svnaim_grndata_grn text NULL,
                svpodrazd_svfilial_svnaim_grndata_valid_from date NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL
            );""",
        "s_local_company_tax_authority_registration_info": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.s_local_company_tax_authority_registration_info (
                svucetno_datapostuc date NULL,
                svucetno_inn bpchar(10) NULL,
                svucetno_kpp bpchar(9) NULL,
                svucetno_grndata_grn text NULL,
                svucetno_grndata_valid_from date NULL,
                svucetno_svno_kodno text NULL,
                svucetno_svno_naimno text NULL,
                ogrn bpchar(13) NULL,
                local_company_pk bpchar(32) NOT NULL,
                load_dtm timestamp NULL,
                rec_src bpchar(5) NULL,
                statement_dt date NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT s_local_company_tax_authority_registration_info_pkey PRIMARY KEY (local_company_pk, hash_diff)
            );""",
        "address_fias_mapping": f"""
            CREATE TABLE  IF NOT EXISTS {var_schem}.address_fias_mapping (
                entity_id text NOT NULL,
                entity_type text NULL,
                hierarchy_fulltext_admin text NULL,
                hierarchy_fulltext_municipal text NULL,
                fias_standardized_address text NULL,
                fias_guid text NULL,
                status text NULL,
                error_message text NULL,
                created_at timestamp NULL,
                updated_at timestamp NULL,
                hash_diff bpchar(32) NOT NULL,
                CONSTRAINT address_fias_mapping_pkey PRIMARY KEY (hash_diff)
            );""",
    }

    with conn_base(var_out) as conn:
        cur = conn.cursor()
        for table_name, sql_tt in tables.items():
            ssql = f"""SELECT to_regclass('{var_schem}.{table_name}') IS NOT NULL AS table_exists"""
            cur.execute(ssql)
            answer = cur.fetchone()[0]
            if answer:
                logger.info(f"Table {table_name} creation failed! Table exist!!")
            else:
                cur.execute(sql_tt)
                conn.commit()
                logger.info(f"Table {table_name} created successfully")
